version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/Sofia
  open-pull-requests-limit: 99
  versioning-strategy: increase
